### ISSUE TITLE
User interface blinking when trying to manage a file

### ISSUE THREAD

**Issue by nkirchner-zeenea** [inrupt/pod-browser#294]
Hello !

When I want to manage a file, the interface on the right is blinking, sometimes so much than I can't do anything.

It occurs on the page `https://podbrowser.inrupt.com/resource/` with `?action=details`.

**Comment by kahramanbayraktar** [comment]
I have had the same problem for weeks. As far as I remember, it was not so before this period of time.

![podbrowser-endless-refresh](https://user-images.githubusercontent.com/10710121/119960378-8fef3c80-bfad-11eb-812d-1d44f18b0370.gif)

**Comment by kevin-inrupt** [comment]
Hi @nkirchner-zeenea & @kahramanbayraktar,

Thanks for contacting us about this, and apologies for the slow response. To help us track down the issue, can you let us know the WebID(s) you are using to log into PodBrowser?

Thanks,

Kevin

**Comment by kahramanbayraktar** [comment]
Hi Kevin,

This is my WebID: https://karr.solidcommunity.net/profile/card#me

Thank you.

**Comment by kevin-inrupt** [comment]
Thanks for the WebID. In our testing of the issue, it seems to only occur when the user is logged into PodBrowser using a WebID from a Node Solid Server (e.g., inrupt.net or (as in your case) solidcommunity.net). We do not see similar problems when logged into PodBrowser using an Enterprise Solid Server WebID. 

Our team are investigating the cause, and we'll keep you updated on progress.

Kevin

**Comment by acailly** [comment]
I tried to understand why the bug occurs and I think that the refresh is caused by the `useEffect` in `src/hooks/useAccessControl/index.jsx` (https://github.com/inrupt/pod-browser/blob/main/src/hooks/useAccessControl/index.jsx#L38)

I see that this `useEffect` has a dependency on `authenticatedProfile` (https://github.com/inrupt/pod-browser/blob/main/src/hooks/useAccessControl/index.jsx#L55), but `authenticatedProfile` is not used in the body of the `useEffect`

`authenticatedProfile` is loaded by `useAuthenticatedProfile` (https://github.com/inrupt/pod-browser/blob/main/src/hooks/useAccessControl/index.jsx#L31) which seems to trigger a fetch, so the result is always different (at least the reference is different even if the content is the same, and because `useEffect` only checks the reference, it triggers every time `useAuthenticatedProfile` is called)

I don't understand why `authenticatedProfile` is retrieved and added to the `useEffect` dependencies
That's a change that appeard in https://github.com/inrupt/pod-browser/pull/243, maybe you could enlight me @megoth ? :grinning:

**Comment by kevin-inrupt** [comment]
@nkirchner-zeenea & @kahramanbayraktar: PodBrowser has been updated to resolve the issue with the Resource details panel 'blinking' when logged into an inrupt.net Pod. Let us know if you are still having issues.

**Comment by nkirchner-zeenea** [comment]
@kevin-inrupt the problem is solved ! Thank you !

**Comment by kahramanbayraktar** [comment]
@kevin-inrupt Yes, it seems to have been solved. Many thanks!
