### ISSUE TITLE
Inrupt doesn't work with Community Solid Server

### ISSUE THREAD

**Issue by joeitu** [inrupt/pod-browser#449]
# context
I'm trying to create a CSS recipe that uses PodBrowser as a CSS UI, I'm trying to run PodBrowser as a client-side app by exporting it in static HTML files. 

# step to reproduce

 1.  git clone the repo, `npm install`
 1. `npm run build`
 1. `cd out/`
 1. `python3 -m http.server 8001`
 
 Now on a browser go to `http://localhost:8001`, the PodBrowser index page should display normally. 

I'll try to login to with my CSS instance host on `localhost:3000` so I enter this address in the correct input and click `GO`

## Expected behaviour

Login to CSS

## Acutal behaviour

Stay on the index page and got two errors in the console:
![image](https://user-images.githubusercontent.com/60817856/156942639-95ad71d1-25b1-4c82-b9c2-2fc5f85ada07.png)

```
    at new e (oidc-client.min.js:1:20295)
    at oidc-client.min.js:1:25906
    at async t.default.handle (AuthorizationCodeWithPkceOidcHandler.js:32:19)
    at async t.default.login (ClientAuthentication.js:16:153)
    at async login (Session.js:47:13)
    at async login (index.js:246:9)
```

**Comment by HsinhungLin** [comment]
It seems that Inrupt Pod Browser can't login to the pod created on CSS.

**Comment by joeitu** [comment]
I have tried CSS v2 and v3 and got the same result. Any idea how this can be fixed?

**Comment by joeitu** [comment]
Actually, It doesn't work with any of the "Sign in with other provider" options, bu tit work with the default Pod Space Sign In button

**Comment by HsinhungLin** [comment]
Since PodBrowser supports NSS. I think the problem is somehow about authentication like DPOP or something.
Unfortunately,  still don't know how to fix it. Just find this sample about how to modified the authentication to DPOP that compatible with CSS 3.0.0.
[https://github.com/jeff-zucker/solid-file-client/blob/master/docs/examples/upload/upload.js](https://github.com/jeff-zucker/solid-file-client/blob/master/docs/examples/upload/upload.js)

**Comment by joeitu** [comment]
Form package.json I can see that Pod Browser uses Inrupt auth library, which is supposed to be compatible with CSS 2 and 3. Or perhaps it is a too old version?

**Comment by HsinhungLin** [comment]
For now, I can login to pod created in solidweb.me, however it shows nothing as follows
![圖片](https://user-images.githubusercontent.com/8468977/158821635-7b9eb371-5411-4505-8b57-35acb8317d52.png)

**Comment by joeitu** [comment]
Yes, actually the issue seems to be that is it not compatible with CSS yet. Maybe the core devs  @ThisIsMissEm @daytonn @VirginiaBalseiro  knows more about it?

**Comment by ThisIsMissEm** [comment]
Also, Pod Browser's localhost `client_id` is set to only allow `:3000` as being where Pod Browser is, see: https://github.com/inrupt/pod-browser/blob/main/clientid.json

**Comment by joeitu** [comment]
> there is a known issue that is that CSS doesn't include the correct scopes supported by default or in certain configurations doesn't. PodBrowser is still affected by that bug that was recently fixed in solid-client-authn-js; We need to upgrade the dependencies here, but there's been some complication in that.

So if I understand correctly the issue comes from Pod browser not using an updated version of `solid-client-authn-js`. But is there also some things to be fixed also on CSS side?

**Comment by ThisIsMissEm** [comment]
CSS either skips the scopes_supported header, or still has `webid` in the scopes supported despite not supporting that scope (my bad, I gave a bad recommendation by accident). We do need to upgrade the SDKs on Pod Browser, but as mentioned there were complications — last time I tried it the other week, it generated a 32k line diff and broke the build toolchain; I'm currently emphasising merging #440 first.

**Comment by ThisIsMissEm** [comment]
But there will likely be an issue due to the port mismatch in the redirectUrls of the `client_id` as pod-browser without any changes expects to run on port 3000

**Comment by ThisIsMissEm** [comment]
I can verify that going to `https://podbrowser.inrupt.com` and logging in with `solidcommunity.net` now works, as they no longer have the `webid` scope in their advertised `scopes_supported` list; You can check this with `curl -X 'GET' -H 'Accept: application/json' -L -v 'http://solidcommunity.net/.well-known/openid-configuration' | jq '.scopes_supported'` (alternatively swap in your own servers' URL there and check that you don't have `webid` as a scope if you're on CSS or NSS, as those don't support that scope afaik).

As for logging in from a locally hosted podbrowser instance, that could be more complicated due to how the login flow works with the [redirect URL setup](https://github.com/inrupt/pod-browser/blob/main/constants/app.js#L33) — running on localhost outside of what our development setup is isn't actively supported right now, and there's likely rough edges.

**Comment by joeitu** [comment]
When running the curl command I get the answer:
```
[
  "openid",
  "profile",
  "offline_access"
]
``` 
On CSS v2

> As for logging in from a locally hosted podbrowser instance, that could be more complicated due to how the login flow works with the [redirect URL setup](https://github.com/inrupt/pod-browser/blob/main/constants/app.js#L33) — running on localhost outside of what our development setup is isn't actively supported right now, and there's likely rough edges.

Would using ngrok bipass this issue?

**Comment by joeitu** [comment]
Actually tried with ngrok making a HTTP proxy and didn't work better. ( only have a free plan so didn't try with TLS )

**Comment by ThisIsMissEm** [comment]
@joeitu the issue is that you're serving PodBrowser on a different port to what the `localhost` one is setup to use, where we also use the new [Client ID Authentication](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-client/) features.

Using ngrok may work, but this isn't something we've tested or support, and even then, you'd need to be using the nextjs server (`npm start`) instead of just serving the compiled assets (which is what you're doing). PodBrowser does have some [server components](https://github.com/inrupt/pod-browser/blob/main/pages/api/app.js) to it, which makes the authentication work.

If you don't need to develop on PodBrowser, I'd really recommend just using the hosted version. If you want a convenient URL to login using your IdP with the hosted PodBrowser, then you can use `https://podbrowser.inrupt.com/login?idp=http://some-idp.com/` which will expand the "other provider" box on the login form with your IdP URL prefilled.

**Comment by ThisIsMissEm** [comment]
And yes, that server component enforces `https`, as that should definitely be used here.

**Comment by joeitu** [comment]
> @joeitu the issue is that you're serving PodBrowser on a different port to what the localhost one is setup to use, where we also use the new [Client ID Authentication](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-client/) features.

Sorry for not updating, but I have also tried on port 3000 and got exactly the same issue.  

> PodBrowser does have some [server components](https://github.com/inrupt/pod-browser/blob/main/pages/api/app.js) to it, which makes the authentication work.

Ok good to know! I think I was missing that part. So as I understand there is no way to use Pod Browser as a standalone client side app. I wrongly assumed that it could be possible.

> If you don't need to develop on PodBrowser, I'd really recommend just using the hosted version.

The end goal is to create a recipe for CSS, so the hosted version isn't working, but good to know the idp URL parameter

**Comment by ThisIsMissEm** [comment]
> > @joeitu the issue is that you're serving PodBrowser on a different port to what the localhost one is setup to use, where we also use the new [Client ID Authentication](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-client/) features.
> 
> Sorry for not updating, but I have also tried on port 3000 and got exactly the same issue.

Did you try running `npm start` instead? The issue is likely that the Client ID for Authentication is not being served.

> > PodBrowser does have some [server components](https://github.com/inrupt/pod-browser/blob/main/pages/api/app.js) to it, which makes the authentication work.
> 
> Ok good to know! I think I was missing that part. So as I understand there is no way to use Pod Browser as a standalone client side app. I wrongly assumed that it could be possible.

Running PodBrowser as a fully client-side only application is not something we actively support. You might be able to get it working by reading through the previously linked guide on Client ID Authentication.

> > If you don't need to develop on PodBrowser, I'd really recommend just using the hosted version.
> 
> The end goal is to create a recipe for CSS, so the hosted version isn't working, but good to know the idp URL parameter

I think this would potentially be because CSS doesn't support WebID nor Client ID Authentication, if I recall correctly.

We primarily develop PodBrowser against ESS, there may be features of the solid spec that we use that aren't implemented by other servers, but ultimately, we haven't been building PodBrowser to be self-hosted, so there's only so much support we can give here, and we cannot recommend self-hosting the application for now.

**Comment by joeitu** [comment]
Got it.  I have a good understanding of the situation now. From my side, the issue can be closed
Thank you so much @ThisIsMissEm for the clear and detailed answer :raised_hands:

**Comment by joeitu** [comment]
> Did you try running npm start instead? 

Yes this work as expected ( with NSS server but of course not with CSS )
