### ISSUE TITLE
Token validation error

### ISSUE THREAD

**Issue by wdantuma** [inrupt/pod-browser#511]
Hi,

I'am implementing Solid OIDC for Identityserver and was testing it with podbrowser, but podbrowser throws an error `Token verification failed: F: signature verification failed` when validating the issued IdToken , i have tested it with two online JWT tools [JSON Web Token Verifier](https://jwt.davetonge.co.uk/) and [JWT](https://jwt.io/) and both state the signature is valid.

The issued IdToken:

`eyJhbGciOiJSUzI1NiIsImtpZCI6IkZFN0QyRkY2ODZDQUQ0QzUwMjgyMTc4OThENzAxMUJFIiwidHlwIjoiSldUIn0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjYzMzMyNDY5LCJpYXQiOjE2NjMzMzI0NjksImV4cCI6MTY2MzMzMjc2OSwiYXVkIjoiaHR0cHM6Ly9wb2Ricm93c2VyLmlucnVwdC5jb20vYXBpL2FwcCIsImFtciI6WyJwd2QiXSwiYXRfaGFzaCI6Im1YcnZmX2VSd1dEczFGSml6dlVoSnciLCJzaWQiOiJFNEIyNERFNEUxOThCNDY0NEREMjQ4NTcyRTU5NEE3QSIsInN1YiI6Ijg4NDIxMTEzIiwiYXV0aF90aW1lIjoxNjYzMzIzMzM4LCJpZHAiOiJsb2NhbCIsImNuZiI6eyJqa3QiOiJtRDVCRWFVdFdXUm92c1dIVm1ha1N5Qy9oSjNHSG8zRG9tUGdIN3dQWm5ZPSJ9fQ.eU9P9vEegUUP9zJU8N9TcNXqU5ue_KrIukRstzP9rQ99E3tJgVf2v0d55HrdvW0aGMUMgU9mSaXN9QAXIPChK631CSlxSys8idKDMi1ZFPTOUr7bfUd4IWFGCl5IaXErcChQHcTCbI-WnTnLfSbFIS_ukUEYxsAJxuohapnLDrXriIhadlyhaA3KWNcGF7yBFFso07nZS_Qtcl2VbjB0Pq11NfPLYu1-pHoSRYIKgNQtPCtSuI298wQnoMraJcOEOfNyqYkY-PuUgpa6lSaY_eqy0fH_VxH8cUUyPh4cxvFCPDE2VXVRenVcStVF4JIaIEI-PZzUV2ZjqOMraubzWw`

The jwks file:

`{
    "keys": [
        {
            "kty": "RSA",
            "use": "sig",
            "kid": "FE7D2FF686CAD4C5028217898D7011BE",
            "e": "AQAB",
            "n": "wPPUSyU6INtbCfkmSMf63Tsg-YV-Mp9w1bjQ1jR-e0JjpVHNS9y84rhpRH4bUK5FL1t_ssN2QpycboVMyvKSA9fVCrFSrJcpPgInmUFi3prOKylnr0e-50om17_Bgn0IXFURd-JXxglyRrbiIlxDrxf1jwo79BenJgiLUOP-Sj5UAAxwqyFANEm3TYcH8g93-L4uh_Ch5gAqE1q80cR0XmHIowMwdn7FU_1TaJ8Qs8tWYHEIZ2jnRDznobo_5zpHraErUelh8GyG3aytVjD4yDwoYebWumBrpRWNjqkHqGzpC-mBwz1V3RpxkWZ-XhhKgMTupX1ghRjpaUkFteJADQ",
            "alg": "RS256"
        }
    ]
}`

**Comment by ThisIsMissEm** [comment]
You'll want to check whether you can interact with this solid server via `@inrupt/solid-client-authn-browser` — it may be because you're on localhost or the `iss` is missing a trailing slash (I think that's required if memory serves); But you would also want to run the [Solid Conformance Test Harness](https://github.com/solid-contrib/conformance-test-harness) against your server, to better see where you stand.

As we cannot access your server, we cannot debug, and we cannot offer further assistance on implementing a server. This is likely not a pod-browser bug.
